# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/mybatis_plus?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456

logging:
  level:
    com.jin.sys: error
    #    com.jin: debug
    org.springframework: info

#  逻辑删除
mybatis-plus:
  mapper-locations: classpath:com/jin/*/mapper/xml/*.xml
  type-aliases-package: com.jin.**.entity
  type-handlers-package: com.jin.handlers
  configuration:
    #    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #MyBatis日志配置
    call-setters-on-nulls: true
    return-instance-for-empty-row: true
  global-config:
    db-config:
      logic-delete-field: logic_flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)